#!/usr/bin/env bash
# Script that transfers a file from our client to a server:
# Acepts 4 parameters:
#   1. The path to the file to be transferred
#   2. The IP of the server we want to transfer the file to
#   3. The username scp connects with
#   4. The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# if less than 4 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 4 ]; then
	file_to_path="$1"
	ip="$2"
	username="$3"
	path_to_ssh_key="$4"
	scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_to_path"\
		"$username@$ip":~/
elif [ "$#" -eq 3 ]; then
	file_to_path="$1"
    ip="$2"
	username="$3"
	scp -o StrictHostKeyChecking=no	 "$file_to_path" "$username@$ip":~/
fi
