#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Hello World
# As an answer file, write a Bash script that configures a new Ubuntu
# machine to respect above requirements
# (this script will be run on the server itself)
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
