#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
FIRST_PATH="server_name _;"
FIRST_PATH_TWO="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
SECOND_PATH="/etc/nginx/sites-available/default"
sudo sed -i "/$FIRST_PATH/a\\$FIRST_PATH_TWO" $SECOND_PATH
sudo service nginx restart
