#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update && sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "/server_name _;/a \\\n\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;"\
	 /etc/nginx/sites-available/default
sudo service nginx start
