#!/usr/bin/env bash
# Not found page 404
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
FIRST_PATH="server_name _;"
FIRST_PATH_TWO="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
SECOND_PATH="/etc/nginx/sites-available/default"
sudo sed -i "/$FIRST_PATH/a\\$FIRST_PATH_TWO" $SECOND_PATH
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo service nginx restart
