#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo bash -c "echo Hello World! > /var/www/html/index.nginx-debian.html"
pattern="server_name _;"
new_string="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404_page.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
file="/etc/nginx/sites-available/default"
sudo sed -i "/$pattern/a\\$new_string" $file
sudo bash -c "echo Ceci n\'est pas une page > /var/www/html/404_page.html"
sudo service nginx restart
