#!/usr/bin/env bash
# that displays script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

LIST="$(ls)"
for i in $LIST
do
	NAME=${i##*-}
	echo "$NAME"
done
